### ISSUE TITLE
Duco Silent en Domoticz 

### ISSUE THREAD

**Issue by broekieman** [martenjacobs/py-duco-mqtt#1]
Ik gebruik domoticz met Rflink en Zigbee gateway.
Kun je mij helpen om de box draadloos te schakelen?
Ik heb nog enkele Sonoff en Shellby schakelaars liggen en ga daarmee proberen de box op stand 3 te schakelen. De schakelaars werken via Mqtt.

**Comment by martenjacobs** [comment]
Deze repo is alleen bruikbaar op een computer die python kan draaien, dus bijvoorbeeld een Raspberry Pi. Ik heb zelf een Pi Zero W in mijn Ducobox geplaatst. Voor jouw toepassing is denk ik genoeg informatie te vinden over hoe het één en ander verbonden kan worden in de README van deze repo. De software is niet ingewikkeld en zul je met wat vrij beschikbare voorbeelden waarschijnlijk zonder veel problemen kunnen opzetten.
